"use client";
import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

// TODO: have a trpc????
import { TRPCReactProvider } from "~/trpc/react";
import { Footer, Heading, Page } from "govuk-react";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

export default function RootLayout({ children }: Readonly) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Page>{children}</Page>
        <div className="flex h-screen"/>
        <Footer />
      </body>
    </html>
  );
}
